# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:

services:
    auth_token_user_provider:
        class:     AppBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:     Doctrine\ORM\EntityManager
        factory:   ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:AuthToken"]

    user_repository:
        class:     Doctrine\ORM\EntityManager
        factory:   ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["AppBundle:User"]

    auth_token_authenticator:
        class:     AppBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false

    gallery.repository:
        class:     AppBundle\Repository\GalleryRepository
        arguments: ["%kernel.root_dir%/../web/", "@logger"]

    cache.controller.listener:
        class: AppBundle\Listener\CacheControllerListener        
        tags:
            - { name: kernel.event_listener, event: kernel.controller }
